-- Security Block 1 — снимок состояния RLS и прав в production
-- Дата снятия: 2026-09-30
-- Project ref: whorwleydkziejjafsea
-- Источник: SQL-пречек 2.6 из аудита Security Block 1
-- Назначение: откат политик и грантов к состоянию до изменений
-- ВАЖНО: перед каждым изменением политик снимать снимок заново
-- Применять: только при откате, в порядке drop новых + create из этого файла
--
-- Охват снимка (как у генератора 2.6):
--   таблицы public: attendance, clubs, groups, kyu_lookup, students,
--   tournament_age_groups, tournament_archive, tournament_archive_groups,
--   tournament_archive_results, tournament_matches, tournament_participants,
--   tournament_weight_groups, tournaments, trainer_groups, trainers;
--   состояние RLS, policies, табличные гранты для anon / authenticated / service_role.
-- НЕ входит в снимок: гранты на отдельные колонки, гранты на функции,
--   другие таблицы JCL (weight_log, archiv, club_payments, sponsors, promo_*,
--   club_monthly_stats, club_yearly_snapshots, delete_candidates и т. д.),
--   таблицы портала (trainer_accounts, families и т. д.), realtime-публикации.
--
-- Строки ниже — вывод генератора без изменений (снята только табличная
-- рамка результата SQL Editor). Файл ничего не отзывает (revoke) и не удаляет
-- (drop): при откате новые policies и гранты удаляются отдельно, см. README.md.

alter table public.attendance enable row level security;
alter table public.clubs disable row level security;
alter table public.groups enable row level security;
alter table public.kyu_lookup enable row level security;
alter table public.students enable row level security;
alter table public.tournament_age_groups enable row level security;
alter table public.tournament_archive enable row level security;
alter table public.tournament_archive_groups enable row level security;
alter table public.tournament_archive_results enable row level security;
alter table public.tournament_matches enable row level security;
alter table public.tournament_participants enable row level security;
alter table public.tournament_weight_groups enable row level security;
alter table public.tournaments enable row level security;
alter table public.trainer_groups enable row level security;
alter table public.trainers enable row level security;
create policy "Allow all trainers delete" on public.trainers as PERMISSIVE for DELETE to anon using (true);
create policy "Allow all trainers insert" on public.trainers as PERMISSIVE for INSERT to anon with check (true);
create policy "Allow all trainers select" on public.trainers as PERMISSIVE for SELECT to anon using (true);
create policy "Allow all trainers update" on public.trainers as PERMISSIVE for UPDATE to anon using (true) with check (true);
create policy "Allow anon insert students" on public.students as PERMISSIVE for INSERT to anon with check (true);
create policy "Allow delete students" on public.students as PERMISSIVE for DELETE to public using (true);
create policy "Allow groups delete" on public.groups as PERMISSIVE for DELETE to anon using (true);
create policy "Allow groups insert" on public.groups as PERMISSIVE for INSERT to anon with check (true);
create policy "Allow groups select" on public.groups as PERMISSIVE for SELECT to anon using (true);
create policy "Allow groups update" on public.groups as PERMISSIVE for UPDATE to anon using (true) with check (true);
create policy "Allow insert attendance" on public.attendance as PERMISSIVE for INSERT to public with check (true);
create policy "Allow insert groups" on public.groups as PERMISSIVE for INSERT to public with check (true);
create policy "Allow insert students" on public.students as PERMISSIVE for INSERT to authenticated with check (true);
create policy "Allow insert trainer_groups" on public.trainer_groups as PERMISSIVE for INSERT to public with check (true);
create policy "Allow read access attendance" on public.attendance as PERMISSIVE for SELECT to public using (true);
create policy "Allow read access groups" on public.groups as PERMISSIVE for SELECT to public using (true);
create policy "Allow read access kyu_lookup" on public.kyu_lookup as PERMISSIVE for SELECT to public using (true);
create policy "Allow read access students" on public.students as PERMISSIVE for SELECT to public using (true);
create policy "Allow read access trainer_groups" on public.trainer_groups as PERMISSIVE for SELECT to public using (true);
create policy "Allow read access trainers" on public.trainers as PERMISSIVE for SELECT to public using (true);
create policy "Allow trainer_groups delete" on public.trainer_groups as PERMISSIVE for DELETE to anon using (true);
create policy "Allow trainer_groups insert" on public.trainer_groups as PERMISSIVE for INSERT to anon with check (true);
create policy "Allow trainer_groups select" on public.trainer_groups as PERMISSIVE for SELECT to anon using (true);
create policy "Allow trainer_groups update" on public.trainer_groups as PERMISSIVE for UPDATE to anon using (true) with check (true);
create policy "Allow update student foto_url" on public.students as PERMISSIVE for UPDATE to public using (true) with check (true);
create policy "Allow update students" on public.students as PERMISSIVE for UPDATE to public using (true) with check (true);
create policy allow_all_age_groups on public.tournament_age_groups as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_all_archive on public.tournament_archive as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_all_archive_groups on public.tournament_archive_groups as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_all_archive_results on public.tournament_archive_results as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_all_matches on public.tournament_matches as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_all_participants on public.tournament_participants as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_all_tournaments on public.tournaments as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_all_weight_groups on public.tournament_weight_groups as PERMISSIVE for ALL to public using (true) with check (true);
create policy clubs_anon_select on public.clubs as PERMISSIVE for SELECT to anon using ((active = true));
grant DELETE on public.attendance to anon;
grant DELETE on public.attendance to authenticated;
grant DELETE on public.attendance to service_role;
grant DELETE on public.clubs to anon;
grant DELETE on public.clubs to authenticated;
grant DELETE on public.clubs to service_role;
grant DELETE on public.groups to anon;
grant DELETE on public.groups to authenticated;
grant DELETE on public.groups to service_role;
grant DELETE on public.kyu_lookup to anon;
grant DELETE on public.kyu_lookup to authenticated;
grant DELETE on public.kyu_lookup to service_role;
grant DELETE on public.students to anon;
grant DELETE on public.students to authenticated;
grant DELETE on public.students to service_role;
grant DELETE on public.tournament_age_groups to anon;
grant DELETE on public.tournament_age_groups to authenticated;
grant DELETE on public.tournament_age_groups to service_role;
grant DELETE on public.tournament_archive to anon;
grant DELETE on public.tournament_archive to authenticated;
grant DELETE on public.tournament_archive to service_role;
grant DELETE on public.tournament_archive_groups to anon;
grant DELETE on public.tournament_archive_groups to authenticated;
grant DELETE on public.tournament_archive_groups to service_role;
grant DELETE on public.tournament_archive_results to anon;
grant DELETE on public.tournament_archive_results to authenticated;
grant DELETE on public.tournament_archive_results to service_role;
grant DELETE on public.tournament_matches to anon;
grant DELETE on public.tournament_matches to authenticated;
grant DELETE on public.tournament_matches to service_role;
grant DELETE on public.tournament_participants to anon;
grant DELETE on public.tournament_participants to authenticated;
grant DELETE on public.tournament_participants to service_role;
grant DELETE on public.tournament_weight_groups to anon;
grant DELETE on public.tournament_weight_groups to authenticated;
grant DELETE on public.tournament_weight_groups to service_role;
grant DELETE on public.tournaments to anon;
grant DELETE on public.tournaments to authenticated;
grant DELETE on public.tournaments to service_role;
grant DELETE on public.trainer_groups to anon;
grant DELETE on public.trainer_groups to authenticated;
grant DELETE on public.trainer_groups to service_role;
grant DELETE on public.trainers to anon;
grant DELETE on public.trainers to authenticated;
grant DELETE on public.trainers to service_role;
grant INSERT on public.attendance to anon;
grant INSERT on public.attendance to authenticated;
grant INSERT on public.attendance to service_role;
grant INSERT on public.clubs to anon;
grant INSERT on public.clubs to authenticated;
grant INSERT on public.clubs to service_role;
grant INSERT on public.groups to anon;
grant INSERT on public.groups to authenticated;
grant INSERT on public.groups to service_role;
grant INSERT on public.kyu_lookup to anon;
grant INSERT on public.kyu_lookup to authenticated;
grant INSERT on public.kyu_lookup to service_role;
grant INSERT on public.students to anon;
grant INSERT on public.students to authenticated;
grant INSERT on public.students to service_role;
grant INSERT on public.tournament_age_groups to anon;
grant INSERT on public.tournament_age_groups to authenticated;
grant INSERT on public.tournament_age_groups to service_role;
grant INSERT on public.tournament_archive to anon;
grant INSERT on public.tournament_archive to authenticated;
grant INSERT on public.tournament_archive to service_role;
grant INSERT on public.tournament_archive_groups to anon;
grant INSERT on public.tournament_archive_groups to authenticated;
grant INSERT on public.tournament_archive_groups to service_role;
grant INSERT on public.tournament_archive_results to anon;
grant INSERT on public.tournament_archive_results to authenticated;
grant INSERT on public.tournament_archive_results to service_role;
grant INSERT on public.tournament_matches to anon;
grant INSERT on public.tournament_matches to authenticated;
grant INSERT on public.tournament_matches to service_role;
grant INSERT on public.tournament_participants to anon;
grant INSERT on public.tournament_participants to authenticated;
grant INSERT on public.tournament_participants to service_role;
grant INSERT on public.tournament_weight_groups to anon;
grant INSERT on public.tournament_weight_groups to authenticated;
grant INSERT on public.tournament_weight_groups to service_role;
grant INSERT on public.tournaments to anon;
grant INSERT on public.tournaments to authenticated;
grant INSERT on public.tournaments to service_role;
grant INSERT on public.trainer_groups to anon;
grant INSERT on public.trainer_groups to authenticated;
grant INSERT on public.trainer_groups to service_role;
grant INSERT on public.trainers to anon;
grant INSERT on public.trainers to authenticated;
grant INSERT on public.trainers to service_role;
grant REFERENCES on public.attendance to anon;
grant REFERENCES on public.attendance to authenticated;
grant REFERENCES on public.attendance to service_role;
grant REFERENCES on public.clubs to anon;
grant REFERENCES on public.clubs to authenticated;
grant REFERENCES on public.clubs to service_role;
grant REFERENCES on public.groups to anon;
grant REFERENCES on public.groups to authenticated;
grant REFERENCES on public.groups to service_role;
grant REFERENCES on public.kyu_lookup to anon;
grant REFERENCES on public.kyu_lookup to authenticated;
grant REFERENCES on public.kyu_lookup to service_role;
grant REFERENCES on public.students to anon;
grant REFERENCES on public.students to authenticated;
grant REFERENCES on public.students to service_role;
grant REFERENCES on public.tournament_age_groups to anon;
grant REFERENCES on public.tournament_age_groups to authenticated;
grant REFERENCES on public.tournament_age_groups to service_role;
grant REFERENCES on public.tournament_archive to anon;
grant REFERENCES on public.tournament_archive to authenticated;
grant REFERENCES on public.tournament_archive to service_role;
grant REFERENCES on public.tournament_archive_groups to anon;
grant REFERENCES on public.tournament_archive_groups to authenticated;
grant REFERENCES on public.tournament_archive_groups to service_role;
grant REFERENCES on public.tournament_archive_results to anon;
grant REFERENCES on public.tournament_archive_results to authenticated;
grant REFERENCES on public.tournament_archive_results to service_role;
grant REFERENCES on public.tournament_matches to anon;
grant REFERENCES on public.tournament_matches to authenticated;
grant REFERENCES on public.tournament_matches to service_role;
grant REFERENCES on public.tournament_participants to anon;
grant REFERENCES on public.tournament_participants to authenticated;
grant REFERENCES on public.tournament_participants to service_role;
grant REFERENCES on public.tournament_weight_groups to anon;
grant REFERENCES on public.tournament_weight_groups to authenticated;
grant REFERENCES on public.tournament_weight_groups to service_role;
grant REFERENCES on public.tournaments to anon;
grant REFERENCES on public.tournaments to authenticated;
grant REFERENCES on public.tournaments to service_role;
grant REFERENCES on public.trainer_groups to anon;
grant REFERENCES on public.trainer_groups to authenticated;
grant REFERENCES on public.trainer_groups to service_role;
grant REFERENCES on public.trainers to anon;
grant REFERENCES on public.trainers to authenticated;
grant REFERENCES on public.trainers to service_role;
grant SELECT on public.attendance to anon;
grant SELECT on public.attendance to authenticated;
grant SELECT on public.attendance to service_role;
grant SELECT on public.clubs to anon;
grant SELECT on public.clubs to authenticated;
grant SELECT on public.clubs to service_role;
grant SELECT on public.groups to anon;
grant SELECT on public.groups to authenticated;
grant SELECT on public.groups to service_role;
grant SELECT on public.kyu_lookup to anon;
grant SELECT on public.kyu_lookup to authenticated;
grant SELECT on public.kyu_lookup to service_role;
grant SELECT on public.students to anon;
grant SELECT on public.students to authenticated;
grant SELECT on public.students to service_role;
grant SELECT on public.tournament_age_groups to anon;
grant SELECT on public.tournament_age_groups to authenticated;
grant SELECT on public.tournament_age_groups to service_role;
grant SELECT on public.tournament_archive to anon;
grant SELECT on public.tournament_archive to authenticated;
grant SELECT on public.tournament_archive to service_role;
grant SELECT on public.tournament_archive_groups to anon;
grant SELECT on public.tournament_archive_groups to authenticated;
grant SELECT on public.tournament_archive_groups to service_role;
grant SELECT on public.tournament_archive_results to anon;
grant SELECT on public.tournament_archive_results to authenticated;
grant SELECT on public.tournament_archive_results to service_role;
grant SELECT on public.tournament_matches to anon;
grant SELECT on public.tournament_matches to authenticated;
grant SELECT on public.tournament_matches to service_role;
grant SELECT on public.tournament_participants to anon;
grant SELECT on public.tournament_participants to authenticated;
grant SELECT on public.tournament_participants to service_role;
grant SELECT on public.tournament_weight_groups to anon;
grant SELECT on public.tournament_weight_groups to authenticated;
grant SELECT on public.tournament_weight_groups to service_role;
grant SELECT on public.tournaments to anon;
grant SELECT on public.tournaments to authenticated;
grant SELECT on public.tournaments to service_role;
grant SELECT on public.trainer_groups to anon;
grant SELECT on public.trainer_groups to authenticated;
grant SELECT on public.trainer_groups to service_role;
grant SELECT on public.trainers to anon;
grant SELECT on public.trainers to authenticated;
grant SELECT on public.trainers to service_role;
grant TRIGGER on public.attendance to anon;
grant TRIGGER on public.attendance to authenticated;
grant TRIGGER on public.attendance to service_role;
grant TRIGGER on public.clubs to anon;
grant TRIGGER on public.clubs to authenticated;
grant TRIGGER on public.clubs to service_role;
grant TRIGGER on public.groups to anon;
grant TRIGGER on public.groups to authenticated;
grant TRIGGER on public.groups to service_role;
grant TRIGGER on public.kyu_lookup to anon;
grant TRIGGER on public.kyu_lookup to authenticated;
grant TRIGGER on public.kyu_lookup to service_role;
grant TRIGGER on public.students to anon;
grant TRIGGER on public.students to authenticated;
grant TRIGGER on public.students to service_role;
grant TRIGGER on public.tournament_age_groups to anon;
grant TRIGGER on public.tournament_age_groups to authenticated;
grant TRIGGER on public.tournament_age_groups to service_role;
grant TRIGGER on public.tournament_archive to anon;
grant TRIGGER on public.tournament_archive to authenticated;
grant TRIGGER on public.tournament_archive to service_role;
grant TRIGGER on public.tournament_archive_groups to anon;
grant TRIGGER on public.tournament_archive_groups to authenticated;
grant TRIGGER on public.tournament_archive_groups to service_role;
grant TRIGGER on public.tournament_archive_results to anon;
grant TRIGGER on public.tournament_archive_results to authenticated;
grant TRIGGER on public.tournament_archive_results to service_role;
grant TRIGGER on public.tournament_matches to anon;
grant TRIGGER on public.tournament_matches to authenticated;
grant TRIGGER on public.tournament_matches to service_role;
grant TRIGGER on public.tournament_participants to anon;
grant TRIGGER on public.tournament_participants to authenticated;
grant TRIGGER on public.tournament_participants to service_role;
grant TRIGGER on public.tournament_weight_groups to anon;
grant TRIGGER on public.tournament_weight_groups to authenticated;
grant TRIGGER on public.tournament_weight_groups to service_role;
grant TRIGGER on public.tournaments to anon;
grant TRIGGER on public.tournaments to authenticated;
grant TRIGGER on public.tournaments to service_role;
grant TRIGGER on public.trainer_groups to anon;
grant TRIGGER on public.trainer_groups to authenticated;
grant TRIGGER on public.trainer_groups to service_role;
grant TRIGGER on public.trainers to anon;
grant TRIGGER on public.trainers to authenticated;
grant TRIGGER on public.trainers to service_role;
grant TRUNCATE on public.attendance to anon;
grant TRUNCATE on public.attendance to authenticated;
grant TRUNCATE on public.attendance to service_role;
grant TRUNCATE on public.clubs to anon;
grant TRUNCATE on public.clubs to authenticated;
grant TRUNCATE on public.clubs to service_role;
grant TRUNCATE on public.groups to anon;
grant TRUNCATE on public.groups to authenticated;
grant TRUNCATE on public.groups to service_role;
grant TRUNCATE on public.kyu_lookup to anon;
grant TRUNCATE on public.kyu_lookup to authenticated;
grant TRUNCATE on public.kyu_lookup to service_role;
grant TRUNCATE on public.students to anon;
grant TRUNCATE on public.students to authenticated;
grant TRUNCATE on public.students to service_role;
grant TRUNCATE on public.tournament_age_groups to anon;
grant TRUNCATE on public.tournament_age_groups to authenticated;
grant TRUNCATE on public.tournament_age_groups to service_role;
grant TRUNCATE on public.tournament_archive to anon;
grant TRUNCATE on public.tournament_archive to authenticated;
grant TRUNCATE on public.tournament_archive to service_role;
grant TRUNCATE on public.tournament_archive_groups to anon;
grant TRUNCATE on public.tournament_archive_groups to authenticated;
grant TRUNCATE on public.tournament_archive_groups to service_role;
grant TRUNCATE on public.tournament_archive_results to anon;
grant TRUNCATE on public.tournament_archive_results to authenticated;
grant TRUNCATE on public.tournament_archive_results to service_role;
grant TRUNCATE on public.tournament_matches to anon;
grant TRUNCATE on public.tournament_matches to authenticated;
grant TRUNCATE on public.tournament_matches to service_role;
grant TRUNCATE on public.tournament_participants to anon;
grant TRUNCATE on public.tournament_participants to authenticated;
grant TRUNCATE on public.tournament_participants to service_role;
grant TRUNCATE on public.tournament_weight_groups to anon;
grant TRUNCATE on public.tournament_weight_groups to authenticated;
grant TRUNCATE on public.tournament_weight_groups to service_role;
grant TRUNCATE on public.tournaments to anon;
grant TRUNCATE on public.tournaments to authenticated;
grant TRUNCATE on public.tournaments to service_role;
grant TRUNCATE on public.trainer_groups to anon;
grant TRUNCATE on public.trainer_groups to authenticated;
grant TRUNCATE on public.trainer_groups to service_role;
grant TRUNCATE on public.trainers to anon;
grant TRUNCATE on public.trainers to authenticated;
grant TRUNCATE on public.trainers to service_role;
grant UPDATE on public.attendance to anon;
grant UPDATE on public.attendance to authenticated;
grant UPDATE on public.attendance to service_role;
grant UPDATE on public.clubs to anon;
grant UPDATE on public.clubs to authenticated;
grant UPDATE on public.clubs to service_role;
grant UPDATE on public.groups to anon;
grant UPDATE on public.groups to authenticated;
grant UPDATE on public.groups to service_role;
grant UPDATE on public.kyu_lookup to anon;
grant UPDATE on public.kyu_lookup to authenticated;
grant UPDATE on public.kyu_lookup to service_role;
grant UPDATE on public.students to anon;
grant UPDATE on public.students to authenticated;
grant UPDATE on public.students to service_role;
grant UPDATE on public.tournament_age_groups to anon;
grant UPDATE on public.tournament_age_groups to authenticated;
grant UPDATE on public.tournament_age_groups to service_role;
grant UPDATE on public.tournament_archive to anon;
grant UPDATE on public.tournament_archive to authenticated;
grant UPDATE on public.tournament_archive to service_role;
grant UPDATE on public.tournament_archive_groups to anon;
grant UPDATE on public.tournament_archive_groups to authenticated;
grant UPDATE on public.tournament_archive_groups to service_role;
grant UPDATE on public.tournament_archive_results to anon;
grant UPDATE on public.tournament_archive_results to authenticated;
grant UPDATE on public.tournament_archive_results to service_role;
grant UPDATE on public.tournament_matches to anon;
grant UPDATE on public.tournament_matches to authenticated;
grant UPDATE on public.tournament_matches to service_role;
grant UPDATE on public.tournament_participants to anon;
grant UPDATE on public.tournament_participants to authenticated;
grant UPDATE on public.tournament_participants to service_role;
grant UPDATE on public.tournament_weight_groups to anon;
grant UPDATE on public.tournament_weight_groups to authenticated;
grant UPDATE on public.tournament_weight_groups to service_role;
grant UPDATE on public.tournaments to anon;
grant UPDATE on public.tournaments to authenticated;
grant UPDATE on public.tournaments to service_role;
grant UPDATE on public.trainer_groups to anon;
grant UPDATE on public.trainer_groups to authenticated;
grant UPDATE on public.trainer_groups to service_role;
grant UPDATE on public.trainers to anon;
grant UPDATE on public.trainers to authenticated;
grant UPDATE on public.trainers to service_role;
